# Generated by Django 5.1.6 on 2025-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('time_slot', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('book_condition', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('book_category', models.CharField(max_length=100)),
                ('expected_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
