# Generated by Django 5.1.6 on 2025-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contactadmin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactadmin',
            name='message',
            field=models.CharField(default=1234, max_length=255),
            preserve_default=False,
        ),
    ]
