# Generated by Django 5.1.6 on 2025-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_book_cover_image_book_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='book',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=11, upload_to='book_covers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Good', 'Used - Good'), ('Used - Acceptable', 'Used - Acceptable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
