# Generated by Django 5.1.6 on 2025-03-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
