# Generated by Django 5.1.6 on 2025-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Personal Development', 'Personal Development'), ('Novels', 'Novels')], max_length=100),
        ),
    ]
