# Generated by Django 5.2.6 on 2025-09-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
