# Generated by Django 5.2.6 on 2025-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Not Selected", max_length=20),
        ),
    ]
