# Generated by Django 5.2.6 on 2025-09-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_order_payment_method"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ordered",
            new_name="is_paid",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="payment_id",
            new_name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="start_date",
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Processing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="home.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ordered_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(default=12, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
